#!/usr/bin/env bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2026 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2026 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ "$BASH_DEBUG" -eq 1 ]] && set -x

function stderror()
{
  echo >&2 "$1"
}

function die()
{
  stderror "$1"
  exit 1
}

function temporal()
{
  TMPI="$(mktemp)"
}

function clean()
{
  rm -f "$TMPI"
}

function read_piped_input()
{
  while IFS= read -r PIPED_INPUT
  do
      echo "$PIPED_INPUT" >> "$TMPI"
  done
}

function defaults()
{
  [[ -n "$MAX"        ]] || MAX='10'
  [[ -n "$ONLY_TOTAL" ]] || ONLY_TOTAL=0
}

function params()
{
  if [[ -z "$1" ]]
  then
    if [[ -t 0 ]]
    then
      if [[ -n "$FILE" ]]
      then
        echo "$FILE" > "$TMPI"
      fi
    else
      read_piped_input
    fi
  else
    echo "$*" | tr ' ' '\n' > "$TMPI"
  fi

  [[ -s "$TMPI" ]] || die "EMPTY INPUT"
}

function count()
{
  while read -r FILE _
  do

    [[ -s "$FILE" ]] || die "EMPTY OR NOT FOUND FILE $FILE"

    WCL="$(wc -l < "$FILE")"
    JQC="$(jq -Mc '.' "$FILE" | wc -l)"
    LEN="$(jq -Mc '. | length' "$FILE")"

    if [[ "$JQC" -eq "$WCL" ]]
    then
      TYP='jsonl'
      TOT="$WCL"
    else
      TYP='json'
      TOT="$LEN"
    fi

    if [[ "$ONLY_TOTAL" ]]
    then
      echo "$TOT"
    else
      printf "%*s %-5s %s\\n" "$MAX" "$TOT" "$TYP" "$FILE"
    fi

  done < "$TMPI"
}

function main()
{
  temporal
  defaults
  params "$@"
  count
}

main "$@"
