#!/usr/bin/env bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2024 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2024 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1090

function stderror()
{
  echo >&2 "$1"
}

function die()
{
  stderror "$1"
  exit 1
}

function jsonArray()
{

TMP="$(mktemp)"
JSON_ARRAY=0

head -1 "$JSON"   > "$TMP"

if grep -qE '^\['   "$TMP"
then

  tail -1 "$JSON" > "$TMP"

  if grep -qE '\]$' "$TMP"
  then
    JSON_ARRAY=1
  fi

fi

rm -f "$TMP" 2>/dev/null

}

[[ -n "$SKIP"       ]] || SKIP=0
[[ -n "$LIMIT"      ]] || LIMIT=10
[[ -n "$DB_USER"    ]] || DB_USER='dev'
[[ -n "$DB_HOST"    ]] || DB_HOST='localhost'
[[ -n "$DB_PASS"    ]] || DB_PASS='dev'
[[ -n "$DB_NAME"    ]] || DB_NAME='test'
[[ -n "$DB_PORT"    ]] || DB_PORT='27017'
[[ -n "$DB_AUTH"    ]] || DB_AUTH='admin'
[[ -n "$DB_CONF"    ]] || DB_CONF='.mng'
[[ -e "$DB_CONF"    ]] && source "$DB_CONF"
[[ -n "$COL"        ]] || COL="$1"
[[ -z "$COL"        ]] && die "EMPTY COL"
[[ -n "$JSON"       ]] || JSON="${COL//.json/}.json"
[[ -z "$2"          ]] || JSON="$2"
[[ -s "$JSON"       ]] || die "EMPTY OR NOT FOUND FILE $JSON"

[[ -n "$JSON_ARRAY" ]] || jsonArray

if ! command -v mongoimport >/dev/null 2>/dev/null
then
  die "NOT FOUND mongoimport"
fi

MONGO_IMPORT='mongoimport'
MONGO_IMPORT+=" --port $DB_PORT"
MONGO_IMPORT+=" --host $DB_HOST"
MONGO_IMPORT+=" --username $DB_USER"
MONGO_IMPORT+=" --password $DB_PASS"
MONGO_IMPORT+=" --db $DB_NAME"
MONGO_IMPORT+=" --authenticationDatabase=$DB_AUTH"
MONGO_IMPORT+=" --collection $COL"
MONGO_IMPORT+=" --file $JSON"

[[ "$JSON_ARRAY" -eq 1 ]] && MONGO_IMPORT+=' --jsonArray'

bash -c "$MONGO_IMPORT" || die "FAILED IMPORT IN $COL FROM $JSON"
