#!/usr/bin/env bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2026 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2026 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ "$BASH_DEBUG" -eq 1 ]] && set -x

BIN="$(basename "$0")"

function usage()
{
cat << EOF

## \`$BIN\` convert _MongoDB_ _ObjectId_ to date in \`ISO8601\` format

### Usage

~~~bash

$BIN OBJECT_ID

~~~

### Examples

~~~bash

$BIN 6997ce300000000000000000
2026-02-20

echo 6997ce300000000000000000 | $BIN
2026-02-20

OID=6997ce300000000000000000 $BIN
2026-02-20

$BIN <<< 6997ce300000000000000000
2026-02-20

echo 6955e3300000000000000000 >  oids
echo 6997ce300000000000000000 >> oids

cat oids
6955e3300000000000000000
6997ce300000000000000000

cat oids | $BIN
2026-01-01
2026-02-20

$BIN < oids
2026-01-01
2026-02-20

~~~
EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

function stderror()
{
  echo >&2 "$1"
}

function die()
{
  stderror "$1"
  exit 1
}

function read_piped_input()
{
  while IFS= read -r PIPED_INPUT
  do
    echo "$PIPED_INPUT" >> "$TMPI"
  done
}

function defaults()
{
  [[ -n "$RGX_DATE" ]] || RGX_DATE='[0-9]{4}\-[0-9]{2}\-[0-9]{2}'
  [[ -n "$RGX_OID"  ]] || RGX_OID='[a-f0-9]{24}'
}

function temporal()
{
  TMPI="$(mktemp)"
}

function clean()
{
  [[ "$BASH_DEBUG" -eq 1 ]] && return
  rm -f "$TMPI"
}

function params()
{
  if [[ -z "$1" ]]
  then
    if [[ -t 0 ]]
    then
      if [[ -n "$OID" ]]
      then
        echo "$OID" >"$TMPI"
      else
        die "EMPTY OID"
      fi
    else
      read_piped_input
    fi
  else
    if [[ -s "$1" ]]
    then
      cp -f "$1" "$TMPI"
    else
      echo "$1" >"$TMPI"
    fi
  fi
}

function oid_to_date()
{
  local EPOCH TIMESTAMP

  [[ "$1" =~ $RGX_OID ]] || die "OID $1 NOT MATCH $RGX_OID"
  TIMESTAMP="${1:0:8}"
  EPOCH="$((16#$TIMESTAMP))"

  date -u -d "@$EPOCH" +"%Y-%m-%d"
}

function oids_to_dates()
{
  local DATE

  while read -r OID EXTRA
  do

    DATE="$(oid_to_date "$OID")"

    if [[ -z "$EXTRA" ]]
    then
      printf "%s\\n" "$DATE"
    else
      printf "%s %s\\n" "$DATE" "$EXTRA"
    fi

  done < "$TMPI"
}

function main()
{
  temporal
  defaults
  params "$@"
  oids_to_dates
  clean
}

main "$@"
